bell-server/controllers/settings.py
from flask import (
    Blueprint, render_template, request, flash, redirect, url_for, make_response, jsonify, json
)
from flask import current_app as app
from flask_security import login_required, roles_required
from flask_login import current_user
from werkzeug.utils import secure_filename
from models import Template, Defaults, Sound, CustomSchedule
from helpers import check_file, weekdays
from datetime import datetime
import re
import os

bp = Blueprint('settings', __name__, url_prefix='/settings')


# weekdays = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]


@bp.route('/templates', methods=('GET', 'POST'))
@login_required
def templates():
    if request.method == "POST":
        new_defaults = [request.form[day] for day in weekdays]
        defaults = Defaults.objects.first()
        defaults.daily_templates = new_defaults
        defaults.save()
        flash("Default templates successfully updated.", "success")
        return redirect(url_for("templates.index"))
    else:
        return render_template('settings/templates/index.html',
                               templates=Template.objects(),
                               defaults=Defaults.objects.first().daily_templates,
                               days=enumerate(weekdays))


# ----- #


@bp.route('/sounds')
@login_required
def list_sounds():
    return render_template("settings/sounds/list.html",
                           sounds=[(s.id, s.name, os.path.basename(s.filepath))
                                   for s in Sound.objects.order_by("+name")],
                           default=Defaults.objects.first().sound)


@bp.route('/sounds/create', methods=('GET', 'POST'))
@login_required
def create_sound():
    if request.method == 'POST':
        file = request.files["file"]
        if not (file and check_file(file, "wav")):
            flash("That filetype is not supported.", "error")
            return redirect(request.url)

        filename = secure_filename(file.filename)
        # TODO: check if filename already exists, or is empty

        if any(Sound.objects(name=request.form['name'])):
            flash("There is already a bell sound with that name.", "error")
            return redirect(request.url)

        real_filepath = os.path.join(app.config['UPLOAD_FOLDER'], "sounds", filename)
        file.save(real_filepath)
        sound = Sound(name=request.form['name'], filepath=real_filepath)
        sound.save()

        if bool(request.form.get('default', False)):
            current_defaults = Defaults.objects.first()
            current_defaults.sound = sound.id
            current_defaults.save()
            flash("Sound successfully created and set as default.", "success")
        else:
            flash("Sound successfully created.", "success")
        return redirect(url_for('settings.list_sounds'))
    else:
        return render_template("settings/sounds/create.html")


@bp.route('/sounds/<id>/delete', methods=('POST',))
@login_required
def delete_sound(id):
    sound = Sound.objects(id=id).first()
    os.remove(sound.filepath)
    sound.delete()
    flash("Sound successfully deleted.", "success")
    return redirect(url_for('settings.list_sounds'))


@bp.route('/sounds/<id>/default', methods=('POST',))
@login_required
def default_sound(id):
    current_defaults = Defaults.objects.first()
    current_defaults.sound = id
    current_defaults.save()
    flash("Sound successfully set as default.", "success")
    return redirect(url_for('settings.list_sounds'))


# ----- #


@bp.route('/backups')
@login_required
@roles_required('admin')
def backups():
    return render_template("settings/backups/index.html")


@bp.route('/backups/import', methods=('POST',))
@login_required
@roles_required('admin')
def import_backup():
    file = request.files["file"]
    if not (file and check_file(file, "json")):
        flash("That filetype is not supported.", "error")
        return redirect(url_for("settings.backups"))

    filename = secure_filename(file.filename)
    if not re.match(r"^backup-\d{4}-\d{2}-\d{2}.json$", filename):
        flash("That doesn't look like a valid backup. Please only submit UNMODIFIED backups to the import function.",
              "error")
        return redirect(url_for("settings.backups"))

    # TODO: Make importing safer and more efficient
    real_filename = os.path.join(app.config['UPLOAD_FOLDER'], "imports", filename)
    file.save(real_filename)

    with open(real_filename) as f:
        d = json.load(f)

        # TODO: This probably messes up everyone else who is currently using the software.
        Sound.objects.delete()
        for s in d['sounds']:
            Sound.from_json(json.dumps(s)).save(force_insert=True)

        Template.objects.delete()
        for t in d['templates']:
            Template.from_json(json.dumps(t)).save(force_insert=True)

        CustomSchedule.objects.delete()
        for cs in d['schedules']:
            CustomSchedule.from_json(json.dumps(cs)).save(force_insert=True)

        Defaults.objects.delete()
        for df in d['defaults']:
            Defaults.from_json(json.dumps(df)).save(force_insert=True)

    flash("If you're seeing this message, it means that you followed all of the instructions correctly and nothing "
          "broke (hopefully). Congratulations!", "success")
    return redirect(url_for("settings.backups"))


@bp.route('/backups/export')
@login_required
@roles_required('admin')
def export_backup():
    # TODO: Surely we can be more efficient than jsonifying it, unjsonifying it, then jsonifying it again
    data = {
        'sounds': json.loads(Sound.objects.to_json()),
        'templates': json.loads(Template.objects.to_json()),
        'schedules': json.loads(CustomSchedule.objects.to_json()),
        'defaults': json.loads(Defaults.objects.to_json())
    }
    response = make_response(jsonify(data))
    response.headers["Content-Disposition"] = f"attachment; filename=backup-{str(datetime.now().date())}.json"
    return response

bell-server/templates/settings/sounds/create.html
{% extends "base.html" %}

{% block title %}Create Sound{% endblock %}

{% block content %}
    <h1>Upload new sound</h1>

    <form method="post" enctype="multipart/form-data" action="/settings/sounds/create" class="form-horizontal"
          id="default_settings">
        <div class="form-group">
            <div class="col-2 col-sm-12"><label class="form-label" for="name">Sound name</label></div>
            <div class="col-6 col-sm-12">
                <input class="form-input" type="text" name="name" id="name" required>
            </div>
        </div>
        <div class="form-group">
            <div class="col-2 col-sm-12"><label class="form-label" for="file">Audio file</label></div>
            <div class="col-6 col-sm-12">
                <input type="file" accept=".wav" name="file" id="file" class="d-block form-input" required>
                Only <code class="d-inline">.wav</code> files will be accepted.
            </div>
        </div>

        <div class="form-group">
            <div class="col-2 col-sm-12"><label class="form-label" for="default">Defaults</label></div>
            <div class="col-10 col-sm-12">
                <label class="form-checkbox">
                    <input type="checkbox" name="default" id="default" onclick="toggle_default_warnings()">
                    <i class="form-icon"></i>
                    <span class="default_toggle">This bell will not be set as the default bell sound</span>
                    <span class="default_toggle d-hide">This bell <strong>will</strong> be set as the new default sound</span>
                    <a href="{{ docs }}/default-sound" target="_blank">(more info)</a>
                </label>
            </div>
        </div>

        <button type="button" id="discard" onclick="toggle_modal('discard_modal')" class="btn btn-error">Discard
        </button>
        <div class="modal" id="discard_modal">
            <a onclick="toggle_modal('discard_modal')" class="modal-overlay" aria-label="Close"></a>
            <div class="modal-container">
                <div class="modal-header">
                    <a onclick="toggle_modal('discard_modal')" class="btn btn-clear float-right" aria-label="Close"></a>
                    <div class="modal-title h5">Discard data</div>
                </div>
                <div class="modal-body">
                    <div class="content">
                        Are you sure you would like to discard this bell sound?
                    </div>
                </div>
                <div class="modal-footer">
                    <a href="/settings/sounds" class="btn btn-error float-left">Discard changes</a>
                    <button type="button" class="btn btn-primary" onclick="toggle_modal('discard_modal')">Continue
                        editing
                    </button>
                </div>
            </div>
        </div>
        <button type="button" id="save" onclick="toggle_modal('create_modal')" class="btn btn-primary float-right">
            Create bell sound
        </button>
        <div class="modal" id="create_modal">
            <a onclick="toggle_modal('create_modal')" class="modal-overlay" aria-label="Close"></a>
            <div class="modal-container">
                <div class="modal-header">
                    <a onclick="toggle_modal('create_modal')" class="btn btn-clear float-right" aria-label="Close"></a>
                    <div class="modal-title h5">Confirm submission</div>
                </div>
                <div class="modal-body">
                    <div class="content" id="warnings">
                        <span class="d-hide default_toggle">Are you sure you would like to set this sound as the default? This will affect <strong>all templates and schedules</strong> that do not have a bell sound explicitly set.</span>
                        <span class="default_toggle">Are you sure that you would like to upload this bell sound?</span>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn float-left" onclick="toggle_modal('create_modal')">Continue
                        editing
                    </button> <!-- todo change when not editing -->
                    <button type="submit" class="btn btn-primary" onclick="toggle_modal('create_modal')">Submit</button>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

bell-server/templates/settings/sounds/list.html
{% extends "base.html" %}

{% block title %}Sounds{% endblock %}

{% block content %}
    <h1>Bell Sounds</h1>

    <a class="btn btn-primary" href="{{ url_for('settings.create_sound') }}">Create new bell sound</a>

    <table class="table">
        <thead>
        <tr>
            <th>Name</th>
            <th>Filename</th>
            <th colspan="2">Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for id, name, filepath in sounds %}
            <tr {% if id == default %}class="active"{% endif %}>
                <td>{{ name }}</td>
                <td>{{ filepath }}</td>
                <td>
                    {% if id == default %}
                        (Currently default)
                    {% else %}
                        <button class="btn btn-link"
                                onclick="toggle_modal('default_modal'); change_action('default_form', '{{ url_for("settings.default_sound", id=id) }}')">
                            Make default
                        </button>
                    {% endif %}
                </td>
                <td {% if id == default %}class="tooltip tooltip-left" data-tooltip="The default bell sound cannot be
deleted. Please make another sound
the default in order to delete this."{% endif %}>
                    <button
                            class="btn btn-link text-error"
                            {% if id == default %}disabled{% endif %}
                            onclick="toggle_modal('delete_modal'); change_action('delete_form', '{{ url_for("settings.delete_sound", id=id) }}')"
                    >Delete
                    </button>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <div class="modal" id="default_modal">
        <a onclick="toggle_modal('default_modal')" class="modal-overlay" aria-label="Close"></a>
        <div class="modal-container">
            <div class="modal-header">
                <a onclick="toggle_modal('default_modal')" class="btn btn-clear float-right" aria-label="Close"></a>
                <div class="modal-title h5">Change default bell sound</div>
            </div>
            <div class="modal-body">
                <div class="content">
                    <p>Are you sure you would like to set this sound as the default? This will affect <strong>all
                        templates and schedules</strong> that do not have a bell sound explicitly set.</p>
                    <p>For more information about what this setting affects, <a href="{{ docs }}/default-sound"
                                                                                target="_blank">see the
                        documentation.</a></p>
                </div>
            </div>
            <div class="modal-footer">
                <form action="" method="post" id="default_form">
                    <button class="btn float-left">Make default</button>
                </form>
                <button type="button" class="btn btn-primary" onclick="toggle_modal('default_modal')">Keep existing
                    defaults
                </button>
            </div>
        </div>
    </div>

    <div class="modal" id="delete_modal">
        <a onclick="toggle_modal('delete_modal')" class="modal-overlay" aria-label="Close"></a>
        <div class="modal-container">
            <div class="modal-header">
                <a onclick="toggle_modal('delete_modal')" class="btn btn-clear float-right" aria-label="Close"></a>
                <div class="modal-title h5">Delete bell sound</div>
            </div>
            <div class="modal-body">
                <div class="content">
                    Are you sure you would like to delete this bell sound? This action is permanent and cannot be
                    undone.
                </div>
            </div>
            <div class="modal-footer">
                <form action="" method="post" id="delete_form">
                    <button class="btn btn-error float-left">Delete sound</button>
                </form>
                <button type="button" class="btn btn-primary" onclick="toggle_modal('delete_modal')">Cancel</button>
            </div>
        </div>
    </div>
{% endblock %}