bell-server/controllers/schedule.py
from flask import (
    Blueprint, render_template, request, flash, redirect, url_for, jsonify
)
from flask_security import login_required
from flask_login import current_user
from models import CustomSchedule, Bell, Sound, Defaults
from datetime import datetime, timedelta

bp = Blueprint('schedule', __name__, url_prefix='/schedule')


@bp.route('/')
@login_required
def index():
    return render_template("schedules/index.html")


@bp.route('/list.json')
@login_required
def list_json():
    start = datetime.strptime(request.args['start'][:10], "%Y-%m-%d").date()
    end = datetime.strptime(request.args['end'][:10], "%Y-%m-%d").date()
    schedules = CustomSchedule.objects(date__gte=start, date__lt=end)
    return jsonify([{
        'id': str(s.id),
        'title': s.name,
        'start': s.date.strftime('%Y-%m-%d')
    } for s in schedules])


@bp.route('/create', methods=('GET', 'POST'))
@login_required
def create():
    if request.method == "POST":
        # TODO: Check that the date isn't in the past
        dates = zip(request.form.getlist('start'), request.form.getlist('end'))
        processed_dates = set()
        for start, end in dates:
            d1 = datetime.strptime(start, "%Y-%m-%d").date()
            d2 = datetime.strptime(end, "%Y-%m-%d").date()
            delta = d2 - d1
            for i in range(delta.days + 1):
                processed_dates.add(d1 + timedelta(days=i))

        for date in processed_dates:
            existing = CustomSchedule.objects(date=date)
            if existing:
                # TODO: Warn user before overwriting
                s = existing.first()
            else:
                s = CustomSchedule(date=date)

            s.name = request.form['name']

            times = request.form.getlist('bell_times')
            names = request.form.getlist('bell_names')
            sound_ids = [i if i != "default" else None
                         for i in request.form.getlist('bell_sound_ids')]
            s.bells = [Bell(time=b[0], name=b[1], sound=b[2])
                       for b in zip(times, names, sound_ids)]
            map(lambda bell: bell.save(), s.bells)

            s.save()

        flash('Custom schedule successfully created.', 'success')
        return redirect(url_for('schedule.index'))
    else:
        default_sound = Sound.objects(id=Defaults.objects.first().sound).first()
        return render_template("schedules/create.html", sounds=Sound.objects(), default_sound=default_sound)


@bp.route('/<id>/edit', methods=('GET', 'POST'))
@login_required
def edit(id):
    return 'Hello World! Editing time!'


@bp.route('/delete', methods=('POST',))
@login_required
def delete():
    start = datetime.strptime(request.form['start'][:10], "%Y-%m-%d").date()
    end = datetime.strptime(request.form['end'][:10], "%Y-%m-%d").date()
    schedules = CustomSchedule.objects(date__gte=start, date__lt=end)

    for schedule in schedules:
        schedule.delete()

    flash("Custom schedules successfully deleted.", "success")
    return redirect(url_for('schedule.index'))

bell-server/templates/schedules/create.html
{% extends "schedules/form.html" %}

{% block title %}New Schedule{% endblock %}

{% block verb %}data{% endblock %}
{% block savebutton %}Create & apply schedule{% endblock %}

bell-server/templates/schedules/form.html
{% extends "base.html" %}

{% block extra_resources %}
    <script src="{{ url_for('static', filename='schedules/create.js') }}" defer></script>
{% endblock %}

{% block content %}
    <h1>{% block title %}Create new schedule{% endblock %}</h1>

    <form method="post" action="{{ url_for("schedule.create") }}" onsubmit="assemble_data(); complete_single_dates()"
          class="form-horizontal" id="template_form">
        <div class="form-group add_margin"> <!-- Name -->
            <div class="col-4 col-sm-12"><label class="form-label" for="name">Name</label></div>
            <div class="col-8 col-sm-12">
                <input class="form-input" name="name" id="name" placeholder="Early assembly" required>
            </div>
        </div>

        {% include "_bells.html" %}

        <label class="form-label" for="date0">Apply the custom schedule the following set of dates:</label>
        <ul id="dates_list"></ul>
        <div class="add_margin">
            <button type="button" class="btn add_margin" onclick="add_single_date()">Add single date</button>
            <button type="button" class="btn add_margin" onclick="add_date_range()">Add date range</button>
        </div>

        <button type="button" id="discard" onclick="toggle_modal('discard_modal')" class="btn btn-error">Discard
        </button>
        <div class="modal" id="discard_modal">
            <a onclick="toggle_modal('discard_modal')" class="modal-overlay" aria-label="Close"></a>
            <div class="modal-container">
                <div class="modal-header">
                    <a onclick="toggle_modal('discard_modal')" class="btn btn-clear float-right" aria-label="Close"></a>
                    <div class="modal-title h5">Discard data</div>
                </div>
                <div class="modal-body">
                    <div class="content">
                        Are you sure you would like to discard all {% block verb %}{% endblock %}?
                    </div>
                </div>
                <div class="modal-footer">
                    <a href="{{ url_for("schedule.index") }}" class="btn btn-error float-left">Discard</a>
                    <button type="button" class="btn btn-primary" onclick="toggle_modal('discard_modal')">Continue
                        editing
                    </button>
                </div>
            </div>
        </div>

        <button type="button" id="save" onclick="toggle_modal('save_modal')"
                class="btn btn-primary float-right add_margin">{% block savebutton %}{% endblock %}</button>
        <div class="modal" id="save_modal">
            <a onclick="toggle_modal('save_modal')" class="modal-overlay" aria-label="Close"></a>
            <div class="modal-container">
                <div class="modal-header">
                    <a onclick="toggle_modal('save_modal')" class="btn btn-clear float-right" aria-label="Close"></a>
                    <div class="modal-title h5">Confirm submission</div>
                </div>
                <div class="modal-body">
                    <div class="content" id="warnings">
                        {% block warnings %}{% endblock %}
                        Are you sure you would like to create the custom schedule and apply it to the selected dates?
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn float-left" onclick="toggle_modal('save_modal')">Continue editing
                    </button>
                    <button type="submit" class="btn btn-primary" onclick="toggle_modal('save_modal'); check_dates()">
                        Save
                    </button>
                </div>
            </div>
        </div>
    </form>

{% endblock %}

bell-server/templates/schedules/index.html
{% extends "base.html" %}

{% block extra_resources %}
    {% if config['ENV'] == 'development' %}
        <link rel="stylesheet" href="{{ url_for('static', filename='vendor/fullcalendar/core/main.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='vendor/fullcalendar/daygrid/main.css') }}">
        <script src="{{ url_for('static', filename='vendor/fullcalendar/core/main.js') }}" defer></script>
        <script src="{{ url_for('static', filename='vendor/fullcalendar/daygrid/main.js') }}" defer></script>
        <script src="{{ url_for('static', filename='vendor/fullcalendar/interaction/main.js') }}" defer></script>
    {% else %}
        <link rel="stylesheet" href="{{ url_for('static', filename='vendor/fullcalendar/core/main.min.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='vendor/fullcalendar/daygrid/main.min.css') }}">
        <script src="{{ url_for('static', filename='vendor/fullcalendar/core/main.min.js') }}" defer></script>
        <script src="{{ url_for('static', filename='vendor/fullcalendar/daygrid/main.min.js') }}" defer></script>
        <script src="{{ url_for('static', filename='vendor/fullcalendar/interaction/main.min.js') }}" defer></script>
    {% endif %}
    <script src="{{ url_for('static', filename='schedules/index.js') }}" defer></script>
{% endblock %}

{% block content %}
    <h1>Bell Schedule</h1>

    <a class="btn btn-primary" href="{{ url_for("schedule.create") }}">Manually create new schedule</a>

    <div class="divider text-center" data-content="OR"></div>

    <p>Alternatively, select one or more dates on the calendar below: (you can select multiple dates by clicking and
        dragging)</p>

    <div id="calendar" class="add_margin"></div>

    <form action="{{ url_for("schedule.delete") }}" method="post">
        <input type="hidden" id="start" name="start">
        <input type="hidden" id="end" name="end">

        <button type="button" class="btn btn-error add_margin d-hide" id="delete_button" onclick="toggle_modal('delete_modal')">
            Delete schedules from selected dates
        </button>
        <div class="modal" id="delete_modal">
            <a onclick="toggle_modal('delete_modal')" class="modal-overlay" aria-label="Close"></a>
            <div class="modal-container">
                <div class="modal-header">
                    <a onclick="toggle_modal('delete_modal')" class="btn btn-clear float-right" aria-label="Close"></a>
                    <div class="modal-title h5">Delete schedules</div>
                </div>
                <div class="modal-body">
                    <div class="content">
                        Are you sure you would like to delete any schedules present on <strong>all</strong> of the
                        selected dates? This action is permanent and cannot be undone.
                    </div>
                </div>
                <div class="modal-footer">
                    <form action="" method="post" id="delete_form">
                        <button class="btn btn-error float-left">Delete schedules</button>
                    </form>
                    <button type="button" class="btn btn-primary" onclick="toggle_modal('delete_modal')">Cancel</button>
                </div>
            </div>
        </div>
    </form>

    <form action="{{ url_for("schedule.create") }}" method="post" onsubmit="extract_days()">
        <button type="submit" class="btn btn-primary add_margin" disabled>
            Create custom schedule for selected dates
        </button>
    </form>
{% endblock %}