bell-server/controllers/users.py
from flask import (
    Blueprint, render_template, redirect, url_for, request, flash
)
from flask_security import login_required, roles_required, utils
from flask_login import current_user
from models import User
from xkcdpass import xkcd_password as xp

bp = Blueprint('users', __name__, url_prefix='/users')


@bp.route('/check_pwd')
@login_required
def check_password():
    if current_user.reset_required:
        flash("You have have requested a password reset. Please change your password now.", "info")
        return redirect(url_for('security.change_password'))
    else:
        print(current_user.reset_required)
        return redirect('/')


@bp.route('/successful_reset')
@login_required
def successful_reset():
    current_user.reset_required = False  # TODO: Handle redirects with next param
    current_user.save()
    return redirect('/')


# ----- #


@bp.route('/')
@login_required
@roles_required('admin')
def list_users():
    return render_template("users/index.html",
                           users=User.objects.order_by("+email"))


@bp.route('/create', methods=('GET', 'POST'))
@login_required
@roles_required('admin')
def create():
    return "Text"


@bp.route('/<id>/reset', methods=('GET', 'POST'))
@login_required
@roles_required('admin')
def reset(id):
    wordfile = xp.locate_wordfile()
    words = xp.generate_wordlist(wordfile=wordfile, min_length=5, max_length=8)
    new_pwd = xp.generate_xkcdpassword(words, numwords=4)

    user = User.objects(id=id).first()
    user.password = utils.hash_password(new_pwd)
    user.reset_required = True
    user.save()
    return render_template("users/reset.html", password=new_pwd)


@bp.route('/<id>/delete', methods=('POST',))
@login_required
@roles_required('admin')
def delete(id):
    user = User.objects(id=id).first()
    user.delete()
    flash("User successfully deleted.", "success")
    return redirect(url_for('users.list_users'))

bell-server/templates/users/index.html
{% extends "base.html" %}

{% block content %}
    <h1>{% block title %}Users{% endblock %}</h1>

    <a class="btn btn-primary add_margin" href="{{ url_for('users.create') }}" disabled>Create new user</a>

    <table class="table">
        <thead>
        <tr>
            <th>Email</th>
            <th>Admin?</th>
            <th colspan="2">Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for user in users %}
            <tr>
                <td>{{ user.email }}</td>
                <td>{{ user.has_role('admin') }}</td>
                {% if user == current_user %}
                    <td><a class="btn btn-link" href="{{ url_for("security.change_password") }}">Change password</a>
                    </td>
                {% else %}
                    <td>
                        <button class="btn btn-link"
                                onclick="toggle_modal('pwd_modal'); change_action('pwd_form', '{{ url_for("users.reset", id=user.id) }}')"
                        >Password Reset
                        </button>
                    </td>
                {% endif %}
                <td>
                    <button class="btn btn-link text-error"
                            onclick="toggle_modal('delete_modal'); change_action('delete_form', '{{ url_for("users.delete", id=user.id) }}')"
                    >Delete
                    </button>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <div class="modal" id="pwd_modal">
        <a onclick="toggle_modal('pwd_modal')" class="modal-overlay" aria-label="Close"></a>
        <div class="modal-container">
            <div class="modal-header">
                <a onclick="toggle_modal('pwd_modal')" class="btn btn-clear float-right" aria-label="Close"></a>
                <div class="modal-title h5">Reset user password</div>
            </div>
            <div class="modal-body">
                <div class="content">
                    Are you sure you would like to trigger a password reset?
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn float-left" onclick="toggle_modal('pwd_modal')">Cancel</button>
                <form action="" method="post" id="pwd_form">
                    <button type="submit" class="btn btn-error">Reset password</button>
                </form>
            </div>
        </div>
    </div>

    <div class="modal" id="delete_modal">
        <a onclick="toggle_modal('delete_modal')" class="modal-overlay" aria-label="Close"></a>
        <div class="modal-container">
            <div class="modal-header">
                <a onclick="toggle_modal('delete_modal')" class="btn btn-clear float-right" aria-label="Close"></a>
                <div class="modal-title h5">Delete user</div>
            </div>
            <div class="modal-body">
                <div class="content">
                    Are you sure you would like to delete this user? This action is permanent and cannot be undone.
                </div>
            </div>
            <div class="modal-footer">
                <form action="" method="post" id="delete_form">
                    <button class="btn btn-error float-left">Delete user</button>
                </form>
                <button type="button" class="btn btn-primary" onclick="toggle_modal('delete_modal')">Cancel</button>
            </div>
        </div>
    </div>
{% endblock %}

bell-server/templates/users/reset.html
{% extends "base.html" %}

{% block content %}
    <h1>{% block title %}Password reset{% endblock %}</h1>

    <p>The user's password was successfully reset. <strong>Please inform them that their new password is as
        follows:</strong></p>

    <pre><code>{{ password }}</code></pre>

    <p>Please note that this is only a temporary password, and the user will be prompted to reset it after their first
        login.</p>

    <p>Once the user has remembered their password, press this button to go back to the users page:</p>

    <a class="btn btn-primary" href="{{ url_for("users.list_users") }}">I'm finished</a>
{% endblock %}